legged_body_planner:
  frame_id : odom # May delete this
  replan : true # Planner replans
  update_rate : 10 # Hz | 10 hz
  dt : 0.01 # Time interval of planner | Don't think this is used atm
  goal_state : [5.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] # Goal state (xyz_dot, ypr_dot, xyz,ypr)
  num_states: 12 # Number of states in rigid body | Most likely delete later
  num_controls: 12 # Number of controls in rigid body
  
multi_command_interface_ros:
  update_rate: 20 # Hz

density_plan:
  goal : [3, 0] # Target position (x,y) | HW [2.6, 0]
  #obs_center : [2.0, -0.125] # List of center of obstacles [1.75, 0.1] | HW: [1.5, 0.1]
  #obs_center : [0.86, -0.125, 2.05, 0.125] # List of center of obstacles
  obs_center: [-10.0, -10.0] # No obs case
  r1 : 0.5 # Parameter for Obstacle region | Original : 1.0 | HW: 0.5
  r2 : 1.0 # Parameter for the outer bound of transition region | Original : 1.5 | HW: 2.0
  alpha : 0.25 # Tuning parameter of Lyapunov V(x)
  gain : 15 # Control multiplier | HW: 10
  saturation : 0.175 # Saturation on control | Sim: 0.3 | HW: 0.045 | Mocap: ||0.1||
  rad_from_goal : 0.15 # Execute switching control in problem formulation
  update_rate : 10 # Hz | Rate of feedback planner
  horizon : 10 # Horizon of feedback planner
  dt : 0.1 # Discretization of continuous formulation of FB controller
  window_size : 21 # Moving average filter window
  alpha1 : 0.98 # First Order filter on states (e.g. yaw)
  alpha2 : 0.1 # First Order filter on time derivative states (e.g. yaw_dot)


# TODO (AZ): Bad to mix ROS and their task.info... not sure how I want to address this
